### ISSUE TITLE
Failed build on RHEL / CentOS 7.4

### ISSUE THREAD

**Issue by remicollet** [nbs-system/snuffleupagus#124]
Using natice gcc 4.8 or gcc 6.2 from devtoolset-6

```C
In file included from /usr/include/php/Zend/zend.h:33:0,
                 from /usr/include/php/main/php.h:35,
                 from /usr/include/php/main/SAPI.h:24,
                 from /builddir/build/BUILD/snuffleupagus-23913af8b66c3bec05f937bb31c72fffe935df05/NTS/php_snuffleupagus.h:18,
                 from /builddir/build/BUILD/snuffleupagus-23913af8b66c3bec05f937bb31c72fffe935df05/NTS/sp_harden_rand.c:1:
/usr/include/php/Zend/zend_alloc.h:53:2: error: unknown type name 'uint'
  uint lineno;
  ^~~~

...
```

**Comment by remicollet** [comment]
Tried tagged version 0.1 and master, against various PHP version (7.0.27, 7.1.13 and 7.2.1)

**Comment by remicollet** [comment]
Found:  deleting the CFLAGS settings in config.m4 allow to build with gcc 6.2 on RHEL-7

Notice: default build options are `-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches`


So https://twitter.com/RemiRepository/status/953574803541319680
(added in https://blog.remirepo.net/pages/PECL-extensions-RPM-status for some users request)

**Comment by jvoisin** [comment]
This should be fixed by bd02d0689190f526c99eee9b35c1335bd96a74af

**Comment by remicollet** [comment]
I confirm, fix OK, tested with gcc 4.4 (RHEL-6), 4.8 (RHEL-7), 7.2 (Fedora 27)

**Comment by jvoisin** [comment]
Wonderful ♥
